Temporarily disable pyright in CI

diff --git a/.github/workflows/pytest.yaml b/.github/workflows/pytest.yaml
--- a/.github/workflows/pytest.yaml
+++ b/.github/workflows/pytest.yaml
@@ -31,10 +31,11 @@ jobs:
         run: |
           make test
 
-      - name: Type check with pyright
-        if: matrix.python-version != '3.7' && steps.install.outcome == 'success' && (success() || failure())
-        run: |
-          make pyright
+      # Temporarily disable type check due issue with pyright and matplotlib.
+      # - name: Type check with pyright
+      #   if: matrix.python-version != '3.7' && steps.install.outcome == 'success' && (success() || failure())
+      #   run: |
+      #     make pyright
 
       - name: Lint with flake8
         if: steps.install.outcome == 'success' && (success() || failure())
