move checks to action that can be used by htmltools

diff --git a/.github/workflows/pytest.yaml b/.github/workflows/pytest.yaml
--- a/.github/workflows/pytest.yaml
+++ b/.github/workflows/pytest.yaml
@@ -3,7 +3,7 @@ name: Run tests
 on:
   workflow_dispatch:
   push:
-    branches: ["main", "rc-*"]
+    branches: ["main", "rc-*", "htmltools_type_changes"]
   pull_request:
     types: [opened, synchronize, reopened, ready_for_review]
   release:
@@ -38,30 +38,34 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Run unit tests
+      - name: Check
         if: steps.install.outcome == 'success' && (success() || failure())
-        run: |
-          make check-tests
+        uses: ./.github/py-shiny/check
 
-      - name: Type check
-        if: steps.install.outcome == 'success' && (success() || failure())
-        run: |
-          make check-types
+      # - name: Run unit tests
+      #   if: steps.install.outcome == 'success' && (success() || failure())
+      #   run: |
+      #     make check-tests
 
-      - name: Lint code
-        if: steps.install.outcome == 'success' && (success() || failure())
-        run: |
-          make check-lint
+      # - name: Type check
+      #   if: steps.install.outcome == 'success' && (success() || failure())
+      #   run: |
+      #     make check-types
 
-      - name: Verify code formatting
-        if: steps.install.outcome == 'success' && (success() || failure())
-        run: |
-          make check-format
+      # - name: Lint code
+      #   if: steps.install.outcome == 'success' && (success() || failure())
+      #   run: |
+      #     make check-lint
 
-      - name: Verify code can run with mypy (not Windows)
-        if: steps.install.outcome == 'success' && (success() || failure()) && matrix.os != 'windows-latest'
-        run: |
-          make ci-check-mypy-can-run
+      # - name: Verify code formatting
+      #   if: steps.install.outcome == 'success' && (success() || failure())
+      #   run: |
+      #     make check-format
+
+      # - name: Verify code can run with mypy (not Windows)
+      #   if: steps.install.outcome == 'success' && (success() || failure()) && matrix.os != 'windows-latest'
+      #   run: |
+      #     make ci-check-mypy-can-run
 
   pypi:
     name: "Deploy to PyPI"
