Use shiny setup helper. Test on workflow files updates

diff --git a/.github/workflows/verify-testing-docs-on-change.yml b/.github/workflows/verify-testing-docs-on-change.yml
--- a/.github/workflows/verify-testing-docs-on-change.yml
+++ b/.github/workflows/verify-testing-docs-on-change.yml
@@ -3,6 +3,7 @@ name: Validate Testing Documentation for changes
 on:
   pull_request:
     paths:
+      - ".github/workflows/verify-testing-docs-on-change.yml"
       - "docs/_quartodoc-testing.yml"
       - "shiny/playwright/controller/**"
 
@@ -21,18 +22,13 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.13"
-
-      - name: Install uv
-        uses: astral-sh/setup-uv@v4
+      - name: Setup py-shiny
+        id: install
+        uses: ./.github/py-shiny/setup
 
       - name: Install dependencies
         run: |
-          uv pip install --system --upgrade pip
-          uv pip install --system -e ".[dev,test,doc]"
+          ci-install-docs
 
       - name: Update testing docs and check for changes
         id: check-docs-changes
@@ -44,8 +40,8 @@ jobs:
           make update-testing-docs
 
           if [[ ! -f testing-documentation-before.json || ! -f shiny/pytest/_generate/_data/testing-documentation.json ]]; then
-          echo "One or both documentation files are missing."
-          exit 1
+            echo "One or both documentation files are missing."
+            exit 1
           fi
 
           # Check if the documentation file has changed
